export const EXECUTABLE_AUGMENT_RUNTIME=Object.freeze({
  'aug-001':{
    executable:true,
    source:'BETA_v0.1',
    effects:[
      {
        id:'aug-001-veteran-valid',
        trigger:'CARD_VALIDATED',
        priority:40,
        condition:{path:'resolved.valid',eq:true},
        operations:[{type:'ADD_RESOURCE',resource:'veteranStreak',amount:1}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-001-veteran-collision-reset',
        trigger:'CARD_VALIDATED',
        priority:41,
        condition:{path:'resolved.invalidReason',eq:'COLLISION'},
        operations:[{type:'SET_RESOURCE',resource:'veteranStreak',amount:0}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-001-veteran-damage',
        trigger:'BEFORE_DAMAGE',
        priority:60,
        condition:{path:'player.publicResources.veteranStreak',gte:2},
        operations:[{type:'MODIFY_DAMAGE',amount:1}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-031':{
    executable:true,
    source:'BETA_v0.1',
    effects:[
      {
        id:'aug-031-toughness-cap',
        trigger:'COMBAT_START',
        priority:10,
        operations:[{type:'SET_RESOURCE_MAX',resource:'toughnessCharges',amount:3}],
        maxTriggers:1,resetScope:'COMBAT',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-031-unyielding-gain',
        trigger:'CARD_VALIDATED',
        priority:45,
        condition:{all:[
          {path:'resolved.valid',eq:true},
          {path:'resolved.collisionImmune',eq:true},
          {path:'resolved.collisionGroupSize',gte:2}
        ]},
        operations:[{type:'SET_RESOURCE',resource:'unyielding',amount:1}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-031-unyielding-block',
        trigger:'BEFORE_PLAYER_DAMAGE',
        priority:10,
        condition:{all:[
          {path:'damageType',eq:'DIRECT'},
          {path:'incomingDamage.amount',gt:0},
          {path:'player.publicResources.unyielding',gte:1}
        ]},
        operations:[
          {type:'MODIFY_INCOMING_DAMAGE',amount:-1},
          {type:'SET_RESOURCE',resource:'unyielding',amount:0}
        ],
        tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-061':{
    executable:true,
    source:'BETA_v0.1',
    effects:[
      {
        id:'aug-061-sneaky-success',
        trigger:'CARD_VALIDATED',
        priority:40,
        condition:{all:[{path:'resolved.valid',eq:true},{path:'resolved.soloLowest',eq:true}]},
        operations:[
          {type:'CAPTURE_RESOURCE',resource:'sneakyStack',field:'sneakyBonus'},
          {type:'SET_RESOURCE',resource:'sneakyStack',amount:1}
        ],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-061-sneaky-reset',
        trigger:'CARD_VALIDATED',
        priority:41,
        condition:{not:{all:[{path:'resolved.valid',eq:true},{path:'resolved.soloLowest',eq:true}]}},
        operations:[{type:'SET_RESOURCE',resource:'sneakyStack',amount:0}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-061-sneaky-damage',
        trigger:'BEFORE_DAMAGE',
        priority:60,
        condition:{path:'resolved.sneakyBonus',gt:0},
        operations:[{type:'MODIFY_DAMAGE',amountPath:'resolved.sneakyBonus'}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-091':{
    executable:true,
    source:'BETA_v0.1',
    effects:[
      {
        id:'aug-091-mana-cap',
        trigger:'COMBAT_START',
        priority:10,
        operations:[{type:'SET_RESOURCE_MAX',resource:'mana',amount:6}],
        maxTriggers:1,resetScope:'COMBAT',
        tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-101':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['WHITE_MAGE'],
    config:{healAmount:1,maxTargetsPerTurn:1,excludeSelf:true},
    effects:[]
  },
  'aug-111':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['REVERSE_MATH'],
    effects:[]
  },
  'aug-041':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['GUARDIAN_WALL'],
    config:{guardedAlliesPerTurn:1,redirectCount:1,redirectDamageMode:'FULL'},
    effects:[]
  },
  'aug-051':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['CRUSH_KNIGHT'],
    config:{crushDamagePerCard:1,crushDamageCap:2},
    effects:[]
  },
  'aug-121':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['BLOOD_FRENZY'],
    config:{bonusDamageOnActualHpCost:2},
    effects:[]
  },
  'aug-131':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['IMMORTAL_FIGHTER'],
    config:{collisionHealCapMode:'MAX_HP',revengeMax:1,revengeBonusDamage:2},
    effects:[]
  },
  'aug-181':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['BOLD_STEAL'],
    effects:[
      {
        id:'aug-181-bold-steal-damage',
        trigger:'BEFORE_DAMAGE',
        priority:55,
        condition:{path:'resolved.stealTargetCount',gte:2},
        operations:[{type:'MODIFY_DAMAGE',amount:2}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T05','NUMBER_MUTATION']
      }
    ]
  },
  'aug-241':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['FULL_BARRAGE'],
    config:{expandedDeck:[1,2,2,3]},
    effects:[]
  },
  'aug-291':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['ONE_HIT_KILL'],
    config:{bonusDamagePerCombo:2,comboMax:3,maxUsesPerCycle:1,consumeOn:'VALID_SUCCESS',preserveComboOnCollision:true},
    effects:[]
  },
  'aug-351':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['RELEASED_DEMON_SWORD'],
    config:{transformThreshold:6,transformedDeck:[2,4,5,6],resetDevourOnCombat:true,returnAfterCardsUsed:4},
    effects:[]
  },
  'aug-321':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['TRANSFUSION'],
    config:{bloodPerValidAttack:1,bloodCost:4,bloodMax:6,healAmount:1,maxTransfusionsPerTurn:1,includeSelf:true},
    effects:[]
  },
  'aug-301':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['FULL_THRALL'],
    effects:[
      {
        id:'aug-301-dominance-cycle',
        trigger:'CARD_VALIDATED',
        priority:35,
        condition:{all:[{path:'resolved.bloodCommandUsed',eq:true},{path:'resolved.valid',eq:true}]},
        operations:[
          {type:'CAPTURE_RESOURCE',resource:'dominance',field:'dominanceBonus'},
          {type:'SET_RESOURCE',resource:'dominance',amount:0},
          {type:'ADD_RESOURCE',resource:'dominance',amount:1}
        ],
        maxTriggers:1,resetScope:'TURN',
        tags:['T05','NUMBER_MUTATION']
      },
      {
        id:'aug-301-dominance-damage',
        trigger:'BEFORE_DAMAGE',
        priority:56,
        condition:{path:'resolved.dominanceBonus',gt:0},
        operations:[{type:'MODIFY_DAMAGE',amountPath:'resolved.dominanceBonus'}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T05','NUMBER_MUTATION']
      }
    ]
  }
});

export function executableAugmentRuntime(augmentId){return EXECUTABLE_AUGMENT_RUNTIME[augmentId]||null;}
