import {GUNNER_CONTRACTS} from './gunner-contracts.js';
import {ADVENTURER_CONTRACTS} from './adventurer-contracts.js';
import {KNIGHT_CONTRACTS} from './knight-contracts.js';
import {ROGUE_CONTRACTS} from './rogue-contracts.js';
import {MAGE_CONTRACTS} from './mage-contracts.js';
import {BERSERKER_CONTRACTS} from './berserker-contracts.js';
import {SEER_CONTRACTS} from './seer-contracts.js';
import {IMP_CONTRACTS} from './imp-contracts.js';
import {GAMBLER_CONTRACTS} from './gambler-contracts.js';
export const EXECUTABLE_AUGMENT_RUNTIME=Object.freeze({
  'aug-001':{
    ...ADVENTURER_CONTRACTS['aug-001'],
    executable:true,
    source:'BETA_v0.1',
    effects:[
      {
        id:'aug-001-veteran-valid',
        trigger:'CARD_VALIDATED',
        priority:40,
        condition:{path:'resolved.valid',eq:true},
        operations:[{type:'ADD_RESOURCE',resource:'veteranStreak',amount:1}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-001-veteran-collision-reset',
        trigger:'CARD_VALIDATED',
        priority:41,
        condition:{path:'resolved.invalidReason',eq:'COLLISION'},
        operations:[{type:'SET_RESOURCE',resource:'veteranStreak',amount:0}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-001-veteran-damage',
        trigger:'BEFORE_DAMAGE',
        priority:60,
        condition:{path:'player.publicResources.veteranStreak',gte:2},
        operations:[{type:'MODIFY_DAMAGE',amount:1}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-002':{executable:true,source:'BETA_v0.1',tooltip:'최대 HP가 1 증가하고 획득 시 HP를 1 회복합니다.',specialHandlers:['CONTENT_005B'],effects:[]},
  'aug-003':{executable:true,source:'BETA_v0.2',tooltip:"전투에서 유효 공격을 2회 연속 성공한 뒤, 3번째부터 연속 성공 공격의 피해가 1 증가합니다. 자신의 공격이 무효가 되면 기록이 초기화됩니다.",specialHandlers:['CONTENT_005B'],effects:[]},
  'aug-004':{executable:true,source:'BETA_v0.2',tooltip:"전투에서 첫 충돌 후 다음 유효 공격에 성공하면 성장 EXP 1을 추가로 얻습니다. 전투당 1회입니다.",specialHandlers:['CONTENT_005B'],effects:[]},
  'aug-031':{
    ...KNIGHT_CONTRACTS['aug-031'],
    effects:[
      {
        id:'aug-031-toughness-cap',
        trigger:'COMBAT_START',
        priority:10,
        operations:[{type:'SET_RESOURCE_MAX',resource:'toughnessCharges',amount:3}],
        maxTriggers:1,resetScope:'COMBAT',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-031-unyielding-gain',
        trigger:'CARD_VALIDATED',
        priority:45,
        condition:{all:[
          {path:'resolved.valid',eq:true},
          {path:'resolved.collisionImmune',eq:true},
          {path:'resolved.collisionGroupSize',gte:2}
        ]},
        operations:[{type:'SET_RESOURCE',resource:'unyielding',amount:1}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T00','REFERENCE']
      },
      {
        id:'aug-031-unyielding-block',
        trigger:'BEFORE_PLAYER_DAMAGE',
        priority:10,
        condition:{all:[
          {path:'damageType',eq:'DIRECT'},
          {path:'incomingDamage.amount',gt:0},
          {path:'player.publicResources.unyielding',gte:1}
        ]},
        operations:[
          {type:'MODIFY_INCOMING_DAMAGE',amount:-1},
          {type:'SET_RESOURCE',resource:'unyielding',amount:0}
        ],
        tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-061':{
    ...ROGUE_CONTRACTS['aug-061'],
    specialHandlers:['ROGUE_V02'],
    effects:[
      {
        id:'aug-061-sneaky-success',
        trigger:'CARD_VALIDATED',
        priority:40,
        condition:{all:[{path:'resolved.valid',eq:true},{path:'resolved.soloLowest',eq:true}]},
        operations:[
          {type:'CAPTURE_RESOURCE',resource:'sneakyStack',field:'sneakyBonus'},
          {type:'ADD_RESOURCE',resource:'sneakyStack',amount:1}
        ],
        maxTriggers:1,resetScope:'TURN',tags:['T00','REFERENCE']
      },
      {
        id:'aug-061-sneaky-reset',
        trigger:'CARD_VALIDATED',
        priority:41,
        condition:{not:{all:[{path:'resolved.valid',eq:true},{path:'resolved.soloLowest',eq:true}]}},
        operations:[{type:'SET_RESOURCE',resource:'sneakyStack',amount:0}],
        maxTriggers:1,resetScope:'TURN',tags:['T00','REFERENCE']
      },
      {
        id:'aug-061-sneaky-damage',
        trigger:'BEFORE_DAMAGE',
        priority:60,
        condition:{path:'resolved.sneakyBonus',gt:0},
        operations:[
          {type:'MODIFY_DAMAGE',amountPath:'resolved.sneakyBonus'},
          {type:'SPEND_RESOURCE',resource:'sneakyStack',amountPath:'resolved.sneakyBonus'}
        ],
        maxTriggers:1,resetScope:'TURN',tags:['T00','REFERENCE']
      }
    ]
  },
  'aug-091':{
    ...MAGE_CONTRACTS['aug-091'],
    effects:[
      {
        id:'aug-091-mana-cap',
        trigger:'COMBAT_START',
        priority:10,
        operations:[{type:'SET_RESOURCE_MAX',resource:'mana',amount:6}],
        maxTriggers:1,resetScope:'COMBAT',
        tags:['T00','REFERENCE']
      }
    ],
    specialHandlers:['MAGE_V02']
  },
  'aug-101':{
    ...MAGE_CONTRACTS['aug-101'],
    specialHandlers:['WHITE_MAGE','MAGE_V02'],
    config:{healAmount:1,maxTargetsPerTurn:1,excludeSelf:true},
    effects:[]
  },
  'aug-111':{
    ...MAGE_CONTRACTS['aug-111'],
    specialHandlers:['REVERSE_MATH','MAGE_V02'],
    effects:[]
  },
  'aug-041':{
    ...KNIGHT_CONTRACTS['aug-041'],
    specialHandlers:['GUARDIAN_WALL','KNIGHT_V02'],
    config:{guardedAlliesPerTurn:1,redirectCount:1,redirectDamageMode:'FULL'},
    effects:[]
  },
  'aug-051':{
    ...KNIGHT_CONTRACTS['aug-051'],
    specialHandlers:['CRUSH_KNIGHT','KNIGHT_V02'],
    config:{crushDamagePerCard:1,crushDamageCap:2},
    effects:[]
  },
  'aug-121':{
    ...BERSERKER_CONTRACTS['aug-121'],
    specialHandlers:['BLOOD_FRENZY','BERSERKER_V02'],
    config:{bonusDamageOnActualHpCost:2},
    effects:[]
  },
  'aug-131':{
    ...BERSERKER_CONTRACTS['aug-131'],
    specialHandlers:['IMMORTAL_FIGHTER','BERSERKER_V02'],
    config:{collisionHealCapMode:'MAX_HP',revengeMax:1,revengeBonusDamage:2},
    effects:[]
  },
  'aug-241':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['FULL_BARRAGE'],
    config:{expandedDeck:[1,2,2,3]},
    effects:[]
  },
  'aug-291':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['ONE_HIT_KILL'],
    config:{bonusDamagePerCombo:2,comboMax:3,maxUsesPerCycle:1,consumeOn:'VALID_SUCCESS',preserveComboOnCollision:true},
    effects:[]
  },
  'aug-331':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['DEVOURING_GHOST_SLASH'],
    config:{extraDevourOnValidGhostSlash:1,levelThreshold:8},
    effects:[]
  },
  'aug-351':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['RELEASED_DEMON_SWORD'],
    config:{transformThreshold:6,transformedDeck:[2,4,5,6],resetDevourOnCombat:true,returnAfterCardsUsed:4},
    effects:[]
  },
  'aug-381':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['AERIAL_ACROBATICS'],
    config:{rechargeValidAttacks:3,postAcrobaticsFirstValidBonusDamage:2},
    effects:[]
  },
  'aug-321':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['TRANSFUSION'],
    config:{bloodPerValidAttack:1,bloodCost:4,bloodMax:6,healAmount:1,maxTransfusionsPerTurn:1,includeSelf:true},
    effects:[]
  },
  'aug-301':{
    executable:true,
    source:'BETA_v0.1',
    specialHandlers:['FULL_THRALL'],
    effects:[
      {
        id:'aug-301-dominance-cycle',
        trigger:'CARD_VALIDATED',
        priority:35,
        condition:{all:[{path:'resolved.bloodCommandUsed',eq:true},{path:'resolved.valid',eq:true}]},
        operations:[
          {type:'CAPTURE_RESOURCE',resource:'dominance',field:'dominanceBonus'},
          {type:'SET_RESOURCE',resource:'dominance',amount:0},
          {type:'ADD_RESOURCE',resource:'dominance',amount:1}
        ],
        maxTriggers:1,resetScope:'TURN',
        tags:['T05','NUMBER_MUTATION']
      },
      {
        id:'aug-301-dominance-damage',
        trigger:'BEFORE_DAMAGE',
        priority:56,
        condition:{path:'resolved.dominanceBonus',gt:0},
        operations:[{type:'MODIFY_DAMAGE',amountPath:'resolved.dominanceBonus'}],
        maxTriggers:1,resetScope:'TURN',
        tags:['T05','NUMBER_MUTATION']
      }
    ]
  },
  ...Object.fromEntries(Object.entries(KNIGHT_CONTRACTS).filter(([id])=>!['aug-031','aug-041','aug-051'].includes(id)).map(([id,contract])=>[id,{...contract,effects:[],specialHandlers:['KNIGHT_V02']}])) ,
  ...Object.fromEntries(Object.entries(ADVENTURER_CONTRACTS).filter(([id])=>id!=='aug-001').map(([id,contract])=>[id,{...contract,effects:[],specialHandlers:['ADVENTURER_V02']}])) ,
  ...Object.fromEntries(Object.entries(ROGUE_CONTRACTS).filter(([id])=>id!=='aug-061').map(([id,contract])=>[id,{...contract,effects:[],specialHandlers:['ROGUE_V02']}])) ,
  ...Object.fromEntries(Object.entries(MAGE_CONTRACTS).filter(([id])=>!['aug-091','aug-101','aug-111'].includes(id)).map(([id,contract])=>[id,{...contract,effects:[],specialHandlers:['MAGE_V02']}])) ,
  ...Object.fromEntries(Object.entries(BERSERKER_CONTRACTS).filter(([id])=>!['aug-121','aug-131'].includes(id)).map(([id,contract])=>[id,{...contract,effects:[],specialHandlers:['BERSERKER_V02']}])) ,
  ...Object.fromEntries(Object.entries(SEER_CONTRACTS).map(([id,contract])=>[id,{...contract,...(id==='aug-161'?{config:{recoverCount:1,targetMode:'EXPLICIT_ALLY',recoverableSources:['BASE'],excludeTemporary:true}}:{}),effects:[],specialHandlers:['SEER_V02']}])) ,
  ...Object.fromEntries(Object.entries(IMP_CONTRACTS).map(([id,contract])=>[id,{...contract,effects:[],specialHandlers:['IMP_V02']}])) ,
  ...Object.fromEntries(Object.entries(GUNNER_CONTRACTS).map(([id,contract])=>[id,{...contract,executable:true,config:id==='aug-241'?{expandedDeck:[1,2,2,3]}:{},effects:[],specialHandlers:['GUNNER_V02']}])) ,
  ...Object.fromEntries(Object.entries(GAMBLER_CONTRACTS).map(([id,contract])=>[id,{...contract,...(id==='aug-237'?{tooltipBetaV02:'올인 성공 공격의 실제 피해가 8 이상이면 다음 드로우 페널티를 1턴 줄입니다(최소 0턴). 전투당 1회.'}:{}),executable:true,effects:[],specialHandlers:['GAMBLER_V02']}])) ,
});

export function executableAugmentRuntime(augmentId){return EXECUTABLE_AUGMENT_RUNTIME[augmentId]||null;}
