import test from 'node:test';
import assert from 'node:assert/strict';
import {F1_MONSTER_DEFINITIONS} from '../supabase/functions/game-api/pve/content-f1.js';
import {F2_MONSTER_DEFINITIONS} from '../supabase/functions/game-api/pve/content-f2.js';
import {newPlayerRunState,newCombatState} from '../supabase/functions/game-api/pve/model.js';
import {publishMonsterIntent,executeMonsterIntent,applyMonsterDamage} from '../supabase/functions/game-api/pve/monster.js';
import {applyMonsterCardRules,prepareMonsterAction,monsterPresentation} from '../supabase/functions/game-api/pve/monster-behavior.js';
import {resolveF2AfterDamage} from '../supabase/functions/game-api/pve/monster-behavior-f2.js';
import {describeMonsterPattern} from '../supabase/functions/game-api/pve/presentation.js';
import {beginTurn,submitCard,resolveBasicTurn} from '../supabase/functions/game-api/pve/combat.js';
function make(id){const def=F1_MONSTER_DEFINITIONS[id]||F2_MONSTER_DEFINITIONS[id],players=Array.from({length:4},(_,seat)=>newPlayerRunState({id:'p'+seat,seat_index:seat,character_id:'adventurer',member_type:'human'}));const run={id:'test',seed:'same-seed',rngCounter:0,phase:'COMBAT',floor:def.floor,depth:1,currentRoomNodeId:'test-node',flame:4,maxFlame:5,players,map:{depthCount:10}};run.combat=newCombatState(players,def.baseHp,def.tier==='ELITE'?'ELITE_COMBAT':'NORMAL_COMBAT',def);publishMonsterIntent(run);return run;}
const cards=(numbers,valid=numbers.map(()=>true))=>numbers.map((finalNumber,i)=>({playerId:'p'+i,finalNumber,valid:valid[i],invalidReason:valid[i]?null:'COLLISION'}));
for(const [mode,numbers,target] of [['LOW',[4,5,2,3],'p1'],['LOW',[4,5,6,5],'p2'],['HIGH',[1,2,4,5],'p0'],['HIGH',[3,2,2,5],'p1'],['LOW',[1,2,3,2],null],['HIGH',[4,5,6,4],null]])test(`Wisp ${mode} ${numbers} selects ${target}`,()=>{const run=make('f2_wisp_lamplighter');run.combat.monster.behaviorState.flameMode=mode;const events=[];applyMonsterCardRules(run,cards(numbers),events);const e=events.find(e=>e.type==='WISP_FLAME_TARGETED');assert.equal(e.selectedPlayerId,target);assert.deepEqual(run.combat.monster.behaviorState.pendingHits,target?[target]:[]);resolveF2AfterDamage(run,events,applyMonsterDamage);const damage=events.filter(e=>e.type==='PLAYER_DAMAGED');assert.equal(damage.length,target?1:0);assert.equal(damage.reduce((n,e)=>n+e.amount,0),target?1:0);assert.ok(damage.every(e=>e.monsterPatternSource==='F2_FLAME'));});
test('Wisp collision still eligible, seat ordering independent of array order and no RNG consumed',()=>{const a=make('f2_wisp_lamplighter'),b=structuredClone(a);b.players.reverse();const c=cards([4,5,2,5],[true,false,true,false]);const x=[],y=[],counter=a.rngCounter;applyMonsterCardRules(a,c,x);applyMonsterCardRules(b,[...c].reverse(),y);assert.equal(x[0].selectedPlayerId,'p1');assert.deepEqual(x,y);assert.equal(a.rngCounter,counter);});
test('Wisp DOWNED cannot be selected; authoritative cue matches hazard mode',()=>{const r=make('f2_wisp_lamplighter');r.players[2].status='DOWNED';const e=[];applyMonsterCardRules(r,cards([4,5,6,5]),e);assert.equal(e[0].selectedPlayerId,'p1');assert.ok(!e[0].candidatePlayerIds.includes('p2'));const p=monsterPresentation(r);assert.deepEqual(p.dangerRange,[4,6]);assert.equal(p.patternMaxTargets,1);assert.match(p.statusText,/最高|최고/);assert.match(p.statusText,/1명/);});
test('Wisp integrated collision turn keeps pattern damage separate from unchanged base action',()=>{const r=make('f2_wisp_lamplighter');beginTurn(r);for(let i=0;i<4;i++){const p=r.players[i],n=[4,5,2,5][i];submitCard(r,p.playerId,p.cardPool.find(c=>c.baseNumber===n).id);}const out=resolveBasicTurn(r),e=out.events.find(e=>e.type==='WISP_FLAME_TARGETED');assert.equal(e.selectedPlayerId,'p1');assert.equal(out.cards.find(c=>c.playerId==='p1').valid,false);assert.equal(out.events.filter(e=>e.type==='PLAYER_DAMAGED'&&e.monsterPatternSource==='F2_FLAME').length,1);assert.ok(out.monsterPattern.targetIds.includes('p1'));});
for(const [before,numbers,valid,expected] of [[0,[1,4,5,6],[true,true,true,true],1],[0,[1,2,3,6],[true,true,true,true],1],[1,[1,4,5,6],[true,true,true,true],2],[2,[4,5,6,4],[true,true,true,true],1],[1,[4,5,6,4],[true,true,true,true],0],[0,[4,5,6,4],[true,true,true,true],0],[1,[1,1,4,5],[false,false,true,true],0]])test(`Echo ${before} ${numbers} becomes ${expected}`,()=>{const r=make('f1_echo_bat'),s=r.combat.monster.behaviorState;s.stacks.echo=before;s.lastValidNumbers=[1,2,3];const e=[];applyMonsterCardRules(r,cards(numbers,valid),e);assert.equal(s.stacks.echo,expected);assert.equal(e[0].type,'ECHO_CHANGED');assert.equal(e[0].delta,expected-before);assert.deepEqual(s.lastValidNumbers,[...new Set(numbers.filter((_,i)=>valid[i]))].sort((a,b)=>a-b));const cue=describeMonsterPattern(r,cards(numbers,valid),0,e);assert.match(cue.label,e[0].repeatedPlayerIds.length?/반복 발생/:/반복 없음/);});
test('Echo threshold, base/boosted AOE and reset contract preserved',()=>{for(const stack of [1,2]){const r=make('f1_echo_bat');r.combat.monster.behaviorState.stacks.echo=stack;r.combat.monster.intent={type:'AOE_DAMAGE',telegraphText:'test',payload:{amount:1}};assert.equal(prepareMonsterAction(r,r.combat.monster.intent).payload.amount,stack===2?2:1);const e=executeMonsterIntent(r);assert.equal(e.filter(e=>e.type==='PLAYER_DAMAGED').length,4);assert.equal(r.combat.monster.behaviorState.stacks.echo,0);assert.equal(r.combat.monster.mechanic.threshold,2);}});
test('Echo reconnect snapshot reproduces state transitions and event',()=>{const a=make('f1_echo_bat');a.combat.monster.behaviorState.lastValidNumbers=[1,3,5];a.combat.monster.behaviorState.stacks.echo=1;const b=JSON.parse(JSON.stringify(a)),x=[],y=[];applyMonsterCardRules(a,cards([1,3,5,6]),x);applyMonsterCardRules(b,cards([1,3,5,6]),y);assert.deepEqual(x,y);assert.deepEqual(a.combat.monster.behaviorState,b.combat.monster.behaviorState);});
