import test from 'node:test';
import assert from 'node:assert/strict';
import {applyParityBellPenalty} from '../supabase/functions/game-api/pve/parity-bell.js';
import {newPlayerRunState,newCombatState} from '../supabase/functions/game-api/pve/model.js';
import {F1_MONSTER_DEFINITIONS} from '../supabase/functions/game-api/pve/content-f1.js';
import {applyMonsterCardRules,monsterPresentation} from '../supabase/functions/game-api/pve/monster-behavior.js';
import {beginTurn,submitCard,resolveBasicTurn} from '../supabase/functions/game-api/pve/combat.js';
function make(){const p=newPlayerRunState({id:'p0',seat_index:0,character_id:'adventurer',member_type:'human'}),def=F1_MONSTER_DEFINITIONS.f1_iron_bell_keeper;const r={id:'bell',seed:'bell',rngCounter:0,phase:'COMBAT',floor:1,depth:1,currentRoomNodeId:'n',flame:4,maxFlame:5,players:[p],map:{depthCount:10}};r.combat=newCombatState([p],def.baseHp,'ELITE_COMBAT',def);return r;}
for(const [phase,expected] of [['ODD',[1,1,3,3,5]],['EVEN',[1,2,2,4,4]]])for(let n=1;n<=5;n++)test(`Bell ${phase} ${n} -> ${expected[n-1]} real damage`,()=>{const r=make();beginTurn(r);r.combat.monster.behaviorState.phase=phase;submitCard(r,'p0',r.players[0].cardPool.find(c=>c.baseNumber===n).id);const out=resolveBasicTurn(r);assert.equal(out.damagePackets.find(p=>!p.followUp).amount,expected[n-1]);assert.equal(out.cards[0].valid,true);});
test('Bell floor applies only to bell-caused zero, preserves other reductions',()=>{for(const [before,expected] of [[0,0],[1,1],[2,1],[4,3]]){const c={parityBellPenalty:1};assert.equal(applyParityBellPenalty(before,c),expected);assert.equal(c.parityBellFloorApplied,before===1);}assert.equal(applyParityBellPenalty(1,{}),1);});
test('Bell invalid/collision card gets no penalty/floor',()=>{const r=make(),c={playerId:'p0',finalNumber:1,valid:false,invalidReason:'COLLISION'};r.combat.monster.behaviorState.phase='EVEN';applyMonsterCardRules(r,[c],[]);assert.equal(c.parityBellPenalty,undefined);});
test('Bell defense independently reduces attack to zero',()=>{const r=make();beginTurn(r);r.combat.monster.behaviorState.phase='EVEN';r.combat.monster.defense=1;submitCard(r,'p0',r.players[0].cardPool.find(c=>c.baseNumber===1).id);const out=resolveBasicTurn(r);assert.equal(out.damagePackets[0].amount,0);assert.equal(out.cards[0].parityBellFloorApplied,false);});
test('Bell metadata leaves other penalty intact and reconnect reproduces it',()=>{const r=make();r.combat.monster.behaviorState.phase='EVEN';const restored=JSON.parse(JSON.stringify(r));for(const run of [r,restored]){const c={playerId:'p0',finalNumber:1,valid:true,monsterDamagePenalty:1};applyMonsterCardRules(run,[c],[]);assert.equal(c.monsterDamagePenalty,2);assert.equal(c.parityBellPenalty,1);assert.equal(applyParityBellPenalty(Math.max(0,1-(c.monsterDamagePenalty-c.parityBellPenalty)),c),0);assert.match(monsterPresentation(run).statusText,/짝수의 종.*홀수 공격 -1/);}});
test('Bell retains alternating phases and identical attack pattern',()=>{const r=make();beginTurn(r);assert.equal(r.combat.monster.behaviorState.phase,'ODD');submitCard(r,'p0',r.players[0].cardPool.find(c=>c.baseNumber===2).id);resolveBasicTurn(r);assert.equal(r.combat.monster.behaviorState.phase,'EVEN');});
