const files = {
  boar: 'iron_boar.png', bat: 'echo_bat.png', hunter: 'cowardly_hunter.png',
  golem: 'Executioner_Golem.png', seer: 'Cursed_Prophet.png', slime: 'Starving_Slime.png',
  goblin: 'Chaos_Goblin.png', mimic: 'Mimic_of_Greed.png',
  f1_armored_boar: 'iron_boar.png', f1_coward_hunter: 'cowardly_hunter.png',
  f1_echo_bat: 'echo_bat.png', f2_cursed_prophet: 'Cursed_Prophet.png',
  f2_hungry_slime: 'Starving_Slime.png', f2_chaos_goblin: 'Chaos_Goblin.png',
  f3_greed_mimic: 'Mimic_of_Greed.png', f3_execution_golem: 'Executioner_Golem.png',
  f1_rusty_ballista: 'f1_rusty_ballista.png',
  f1_gate_guard_dog: 'f1_gate_guard_dog.png',
  f1_sewer_rat_swarm: 'f1_sewer_rat_swarm.png',
  f1_graveyard_sentinel: 'f1_graveyard_sentinel.png',
  f1_chain_jailer: 'f1_chain_jailer.png',
  f1_siege_captain: 'f1_siege_captain.png',
  f1_iron_bell_keeper: 'f1_iron_bell_keeper.png',
  f1_fallen_lord: 'f1_fallen_lord.png',
  f1_gatebreaker_colossus: 'f1_gatebreaker_colossus.png',
  f2_spore_acolyte: 'f2_spore_acolyte.png',
  f2_swamp_leech: 'f2_swamp_leech.png',
  f2_mycelium_doppelganger: 'f2_mycelium_doppelganger.png',
  f2_wisp_lamplighter: 'f2_wisp_lamplighter.png',
  f2_thorn_dryad: 'f2_thorn_dryad.png',
  f2_rootjaw_hydra: 'f2_rootjaw_hydra.png',
  f2_thread_witch: 'f2_thread_witch.png',
  f2_rottenheart_ancient: 'f2_rottenheart_ancient.png',
  f2_moon_eating_witch: 'f2_moon_eating_witch.png',
  // Public Beta F3 uses existing painted art until dedicated variants arrive.
  f3_royal_tax_collector: 'Chaos_Goblin.png',
  f3_abyss_duelist: 'f1_fallen_lord.png',
  f3_black_choir: 'Cursed_Prophet.png',
  f3_skillfeed_familiar: 'echo_bat.png',
  f3_abyss_archivist: 'Cursed_Prophet.png',
  f3_royal_appraiser: 'Chaos_Goblin.png',
  f3_abyss_auditor: 'Cursed_Prophet.png',
  f3_null_choir_priest: 'f1_iron_bell_keeper.png',
  f3_abyss_king: 'f1_fallen_lord.png',
  f3_masked_queen: 'f2_moon_eating_witch.png',
};
export const MONSTER_IMAGES = Object.fromEntries(Object.entries(files).map(([shape,file]) =>
  [shape,new URL(`../monster/${file}`,import.meta.url).href]));
